# Generated by Django 3.1.4 on 2021-01-07 06:44

import api.validate_token
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('cnt', models.BigIntegerField()),
                ('construction', models.CharField(max_length=20)),
                ('listedDate', models.DateTimeField()),
                ('lastPrice', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=50, validators=[api.validate_token.validate_token])),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
