# Generated by Django 3.1.4 on 2021-01-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='construction',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='stock',
            name='lastPrice',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='stock',
            name='state',
            field=models.CharField(max_length=64),
        ),
    ]
