# Generated by Django 3.1.4 on 2020-12-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20201222_1419'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Position',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='position',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_code',
        ),
        migrations.AddField(
            model_name='employee',
            name='hobby',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
