# Generated by Django 3.1.4 on 2021-01-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlingKeyword',
            fields=[
                ('keyword', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='keyword to search in naver news api')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024, unique=True, verbose_name='url of news provider')),
                ('crawled_date', models.DateTimeField(verbose_name='crawled date')),
                ('head_text', models.TextField(verbose_name='head text')),
                ('body_text', models.TextField(verbose_name='body text of news')),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
