# Generated by Django 3.1.4 on 2021-03-07 14:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlingKeyword',
            fields=[
                ('keyword', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='keyword to search in naver news api')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('url', models.URLField(max_length=1024, primary_key=True, serialize=False, verbose_name='url of news provider')),
                ('crawled_date', models.DateTimeField(verbose_name='crawled date')),
                ('posted_date', models.DateTimeField(verbose_name='posted_date')),
                ('head_text', models.TextField(verbose_name='head text')),
                ('body_text', models.TextField(verbose_name='body text of news')),
            ],
        ),
        migrations.CreateModel(
            name='NewsKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024, verbose_name='url of news provider')),
                ('keyword', models.CharField(max_length=128, verbose_name='keyword to search in naver news api')),
            ],
            options={
                'unique_together': {('url', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='classification date')),
                ('rank', models.IntegerField(verbose_name='classification rank')),
                ('news_url', models.ForeignKey(db_column='news_url', on_delete=django.db.models.deletion.CASCADE, related_name='news_url', to='crawler.news')),
            ],
        ),
    ]
