# Generated by Django 3.1.4 on 2021-03-07 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='news_url',
            field=models.ForeignKey(db_column='url', default='http://ww.naver.com', on_delete=django.db.models.deletion.CASCADE, related_name='news_url', to='crawler.news'),
            preserve_default=False,
        ),
    ]
