# Generated by Django 3.1.4 on 2021-02-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.URLField(max_length=1024, verbose_name='url of news provider')),
                ('keyword', models.CharField(max_length=128, verbose_name='keyword to search in naver news api')),
            ],
        ),
    ]
