# Generated by Django 3.1.4 on 2021-02-21 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20210221_0524'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newskeyword',
            unique_together={('url', 'keyword')},
        ),
    ]
