# Generated by Django 3.1.4 on 2021-03-03 10:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_news_posted_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='classification date')),
                ('rank', models.IntegerField(verbose_name='classification rank')),
                ('news_url', models.ForeignKey(db_column='news_url', on_delete=django.db.models.deletion.CASCADE, related_name='news_url', to='crawler.news')),
            ],
        ),
        migrations.DeleteModel(
            name='Recommend',
        ),
    ]
